#operations on matrix
import numpy as np
a=np.array(input('enter the 2*2 matrix:'))
b=np.array(input('enter the 2*2 matrix:'))
print('the elemet wise addition of matrix:')
print(np.add(a,b))
print('the elemet wise subtraction of matrix:')
print(np.subtract(a,b))
print('the elemet wise division of matrix:')
print(np.divide(a,b))
print('the elemet wise mutiplication of matrix:')
print(np.multiply(a,b))
print('the elemet wise dot of matrix:')
print(np.dot(a,b))
print('the elemet wise sqaure root of matrix:')
print(np.sqrt(a))
print('the elemet wise transpose of matrix:')
print(a.T)
print('the elemet wise trace of matrix:')
print(np.trace(a))
#numpy for linear Algebraic
print('the determinant of matrix:')
C=np.linalg.det(a)
print(C)
print('the rank of matrix:')
D=np.linalg.matrix_rank(a)
print(D)
print('the inverse of matrix:')
E=np.linalg.inv(a)
print(E)
print('the power of matrix:')
F=np.linalg.matrix_power(a,3)
print(F)


